### ISSUE TITLE
A problem for  input

### ISSUE THREAD

**Issue by cx781086481** [BMIRDS/deepslide#11]
Hello! I'm a new learner for this. I have a question for the input in this resnet and what's your input in the net. Now  I have 1070 .svs folders which contain many patches(for example 1_1.tiff),how should I change my folder and patch to adapt to your net. Thanks for your reply.

**Comment by jasonwei20** [comment]
So the input for the model training is `train_folder`. It's structured like this (see `config.py`):

```
#this is the input for model training, automatically built 
train_folder = 'train_folder' 
train_patches = 'train_folder/train'
val_patches = 'train_folder/val'
```

If your classes are `pos` and `neg`, then `train_folder/train` should have a folder `pos` with patches of positive examples and a folder `neg` with patches negative examples. Your patches should be `png` or `jpg` or something like that, probably not `svs` or `tiff`.
