### ISSUE TITLE
Create subfolders in 'all_wsi'

### ISSUE THREAD

**Issue by Shawnmhy** [BMIRDS/deepslide#19]
Hi Wei,

I am a little bit confused about the input for '1_split.py'.

In the script you mentioned that all_wsi needs to include subfolders of images labeled by class. What do you mean by 'class' here? do you mean training, testing or validation?

And as for the image format, I assume it should .svs not .jpg, right?

**Comment by jasonwei20** [comment]
Class means cancerous, non-cancerous, etc, not training/validation/test.

You need to convert your images to jpg, as svs is not accepted. You can use this to convert: https://github.com/BMIRDS/deepslide/blob/master/code/z_preprocessing/2_svs_to_jpg_tiles.py
