### ISSUE TITLE
Validation Confusion Matrix on 3_train.py

### ISSUE THREAD

**Issue by braulioarredondo** [BMIRDS/deepslide#22]
Hi, I have tested the repository for some months ago. I only have 2 different classes of tissues. I started to test the code with only 1 wsi per class. It runs without any inconvenience. Now, I have started to use 20 wsi per class, but at the moment of printing the validation confusion matrix only one class appears, with a result, at the other class only prints 0.00 0.00. I have tried with different wsi, 20 in all the experiments, but it only changes the class wich prints 0.00 0.00, I attach some images.

I have verified that at the trainfolder/val/Class1 and trainfolder/val/Class2 there are the corresponding images of each class. Even the total number of validation images is the same that is printed at the beggining of the execution. 

Also I received some warnings but I consider are not transcendent for the experiment. 

Last question, I can not use a 32 layer cnn. Is it not abble to use? I can only experiment with 18 and 50 .

Regards! Thanks for your great apportation. :D

![2](https://user-images.githubusercontent.com/31326976/72211720-97d03e80-3495-11ea-92a9-2643520f6b4b.png)

![1 ](https://user-images.githubusercontent.com/31326976/72211721-97d03e80-3495-11ea-9333-1f28eb3c78c1.png)

**Comment by jasonwei20** [comment]
> Last question, I can not use a 32 layer cnn. Is it not abble to use? I can only experiment with 18 and 50 .

You can use ResNet-34 as implemented by default in PyTorch. You can of course use a custom CNN, but that might require modifications to the code :)

> at the moment of printing the validation confusion matrix only one class appears, with a result, at the other class only prints 0.00 0.00

I think this is a known issue that someone told me about, but I will default to @JosephDiPalma to help you

**Comment by JosephDiPalma** [comment]
You will need to pull the latest version of the code for the validation confusion matrix fix.  The old code computed incorrect confusion matrices with more than 10,000 inputs.

**Comment by braulioarredondo** [comment]
> > Last question, I can not use a 32 layer cnn. Is it not abble to use? I can only experiment with 18 and 50 .
> 
> You can use ResNet-34 as implemented by default in PyTorch. You can of course use a custom CNN, but that might require modifications to the code :)
> 
> > at the moment of printing the validation confusion matrix only one class appears, with a result, at the other class only prints 0.00 0.00
> 
> I think this is a known issue that someone told me about, but I will default to @JosephDiPalma to help you

**Comment by braulioarredondo** [comment]
Thank you, Now I can use ResNet-34.

Also, I download the new code version.  The results and accuracy does not change since the first iteration, The only change I see is the learning rate. Insted of 0.00  now is 1.00 in both classes. 

I hve read the 3_train.py code and utils_model.py and there is something about the print options.  I am trying but I can not achive to print the correct accuracy and confusion matrix. :/  


![Anotación 2020-01-12 124409](https://user-images.githubusercontent.com/31326976/72223864-3cf02300-3539-11ea-9721-14ad4a6c73f4.png)

**Comment by JosephDiPalma** [comment]
@braulioarredondo Can you try to print `train_running_loss` in line 272 of `utils_model.py` and see if it ever changes?

**Comment by braulioarredondo** [comment]
> @braulioarredondo Can you try to print `train_running_loss` in line 272 of `utils_model.py` and see if it ever changes?

Hi @JosephDiPalma, I have done it,  I have printed the train_running_loss and the attributes to calculate it (train_loss.item() and  train_inputs.size(0)). But still being not a number. Concretly from the train_loss.item(). 

![Anotación 2020-01-13 131329](https://user-images.githubusercontent.com/31326976/72284521-c91c4c00-3606-11ea-87c7-95c7e9317d88.png)
![Anotación 2020-01-13 131531](https://user-images.githubusercontent.com/31326976/72284522-c9b4e280-3606-11ea-96df-5af66d51a93c.png)

**Comment by JosephDiPalma** [comment]
@braulioarredondo Can you send me the print out of the hyperparameters?

**Comment by braulioarredondo** [comment]
Sure 
![Anotación 2020-01-13 132425](https://user-images.githubusercontent.com/31326976/72285721-506abf00-3609-11ea-9c5e-600d924ddfcb.png)

**Comment by JosephDiPalma** [comment]
@braulioarredondo The problem is that the `path_mean` and `path_std` are 0 for some dimensions.  When the images are being normalized, they are being divided by 0 resulting in `inf`s being present.

**Comment by braulioarredondo** [comment]
Yes thank's, I used --keep_orig_copy=False, so there was nothing on the wsi folder, that was the reason of the 0's. Now I have a wsi's copy on the all_wsi folder. But  I have a issue that I think is common on pytorch.

![image](https://user-images.githubusercontent.com/31326976/72304661-de10d380-3636-11ea-89ce-80f51d738f75.png)

Did you have a related issue like that? Do you have a recommendation for this case? 

* If I change num_workers to 0  at `compute_stats.py` it just obtain a ^C interruption on the console at the middle of the process.

**Comment by JosephDiPalma** [comment]
> Yes thank's, I used --keep_orig_copy=False, so there was nothing on the wsi folder, that was the reason of the 0's.

Thanks for figuring out the issue when using `--keep_orig_copy=False`.  I'll fix that in an upcoming version.  


> Did you have a related issue like that? Do you have a recommendation for this case?
> 
> * If I change num_workers to 0  at `compute_stats.py` it just obtain a ^C interruption on the console at the middle of the process.

I did not have this issue for this code.  Make sure your system isn't running out of RAM, since I've seen this error before in PyTorch when out of memory.

**Comment by braulioarredondo** [comment]
I have increased the ram, and  there is an improvement. But I think the big change that I had to do was compress more the WSI-jpg image sizes. Now it looks good. Thank you for the help. 👍 :D
