### ISSUE TITLE
Fixing print statement

### ISSUE THREAD

**Issue by jasonwei20** [BMIRDS/deepslide#24]
@JosephDiPalma 

If I'm not wrong, you need a `\n` after the print statement in `config.py` here:
```
f"{chr(10).join(f'{k}:{chr(9)}{v}' for k, v in vars(args).items())}"
```

**Comment by JosephDiPalma** [comment]
No `\n` is needed.  I used `chr(10)` which returns the newline character since f-strings don't support a backslash inside them.

**Comment by jasonwei20** [comment]
I didn't check but to my knowledge `"x".join(["a", "b", "c"])` returns `axbxc`, so there would be no new line at the end of that line. 

Also your f-string on the next line has a backslash?
```
f"device:\t{device}\n"
```

**Comment by JosephDiPalma** [comment]
@jasonwei20 I see what you're saying.  Yes, this is incorrect and there should be a `\n`.  Thanks for finding this.

**Comment by JosephDiPalma** [comment]
@jasonwei20 Fixed.
