### ISSUE TITLE
AttributeError: Can't pickle local object 'compute_stats.<locals>.MyDataset'

### ISSUE THREAD

**Issue by SoNanm** [BMIRDS/deepslide#27]
Hi Wei!
I am new to deeplearning classification, thank you for your code and explanations, they are very clear to understand. But I kept ran into errors like this:

> (Torch) C:\Windows>Traceback (most recent call last):
> 
>   File "<string>", line 1, in <module>
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 99, in spawn_main
>     new_handle = reduction.steal_handle(parent_pid, pipe_handle)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\reduction.py", line 82, in steal_handle
>     _winapi.PROCESS_DUP_HANDLE, False, source_pid)
> OSError: [WinError 87] The parameter is incorrect
> C:/Users/Liang/Anaconda3/envs/Torch/python.exe //scallop/User/Liang/Code/Python/deepslide-master/code/config.py
> Traceback (most recent call last):
>   File "//scallop/User/Liang/Code/Python/deepslide-master/code/config.py", line 369, in <module>
>     image_ext=args.image_ext)
>   File "\\scallop\User\Liang\Code\Python\deepslide-master\code\compute_stats.py", line 98, in compute_stats
>     shuffle=False))
>   File "\\scallop\User\Liang\Code\Python\deepslide-master\code\compute_stats.py", line 83, in online_mean_and_sd
>     for data in loader:
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
>     w.start()
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
>     reduction.dump(process_obj, to_child)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> AttributeError: Can't pickle local object 'compute_stats.<locals>.MyDataset'
> 
> (Torch) C:\Windows>Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "\\scallop\User\Liang\Code\Python\deepslide-master\code\config.py", line 369, in <module>
>     image_ext=args.image_ext)
>   File "\\scallop\User\Liang\Code\Python\deepslide-master\code\compute_stats.py", line 98, in compute_stats
>     shuffle=False))
>   File "\\scallop\User\Liang\Code\Python\deepslide-master\code\compute_stats.py", line 83, in online_mean_and_sd
>     for data in loader:
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
>     w.start()
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\process.py", line 112, in start
>     self._popen = self._Popen(self)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\context.py", line 223, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
>     _check_not_importing_main()
>   File "C:\Users\Liang\Anaconda3\envs\Torch\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.

I could only fix the RuntimeError by adding:
`  if __name__ == '__main__':`
But I cannot fix the

>  AttributeError: Can't pickle local object 'compute_stats.<locals>.MyDataset'

Could you help me with this issue?

**Comment by JosephDiPalma** [comment]
@SoNanm Try setting `num_workers=0` in line `99` of `compute_stats.py`.

**Comment by SoNanm** [comment]
Thank you so much, that fixed the problem.

**Comment by JosephDiPalma** [comment]
@SoNanm The `num_workers` option controls the number of processes created. By setting it to `0`, only one process is used for both running the code and the dataloading. In Windows, setting `num_workers` to something other than 0 usually causes the errors above.
