### ISSUE TITLE
Newer scipy versions: cannot import name 'imsave' from 'scipy' (in preprocessing script 2)

### ISSUE THREAD

**Issue by LiesMH** [BMIRDS/deepslide#29]
The z_preprocessing 2. svs_to_jpeg_tiles.py code is not working with the newer versions of scipy. When they updated to scipy 1.2.0 (now 1.4.0) scipy.misc.imsave was removed. Maybe it could be fixed by using imageio.imwrite instead?

Raises error in line 8 of the script: 
>>> from scipy.misc import imsave
Traceback (most recent call last):
  File "<pyshell#44>", line 1, in <module>
    from scipy import imsave
ImportError: cannot import name 'imsave' from 'scipy'

**Comment by JosephDiPalma** [comment]
Fixed in newest commit.
