### ISSUE TITLE
Single Layer TIF format

### ISSUE THREAD

**Issue by jlevy44** [BMIRDS/deepslide#3]
What would you recommend for splitting up single layer TIF file into multiple jpeg tiles? I'm trying to run your preprocessing script, but am getting:

openslide.OpenSlide('X.tif')
Traceback (most recent call last):
...
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

I read somewhere that this command would still work for multilayer TIFs.

Thanks!

**Comment by jlevy44** [comment]
Nevermind, I think I have my workaround: convert X.tif -define tiff:tile-geometry=256x256 -compress jpeg 'ptif:o.tif' . Feel free to critique.

**Comment by RajatGarg45** [comment]
I have an error saying -
SyntaxError: not an FPX file; bad root CLSID

I have my dataset in tiff file format. Do I need to convert my dataset in CFX file format? Please suggest a work around.
