### ISSUE TITLE
question about method

### ISSUE THREAD

**Issue by wangtaoknight** [BMIRDS/deepslide#31]
First, thanks for your hard work and share the entire code on github. I was just begain to studing this process and gain mauch from your work!
I tried to run your code. I see that you don't use the labeling information of the lesion. You are using WSI_ Is every patch defined as tumor? But tumor_ Most WSI are normal tissues. Is that what you do?

**Comment by JosephDiPalma** [comment]
@wangtaoknight 
We are not using the WSI in the dataset in the paper.  The pathologists provided us with annotated regions consisting only of the tissues.  The `WSI` labelling throughout the code is not entirely accurate for the case presented in the paper.  But, this code can still be used for tissues or even whole slides and achieve good performance.

**Comment by wangtaoknight** [comment]
Oh, I got it.  thanks for your reply.
