### ISSUE TITLE
inference instructions; pretrained weights (see https://github.com/BMIRDS/deepslide/issues/35)

### ISSUE THREAD

**Issue by GeorgeBatch** [BMIRDS/deepslide#36]
Hello!

Thank you for making this repository! Do you think you could provide more detailed instructions on how to run the inference? I found the instructions here https://github.com/BMIRDS/deepslide#4-testing-on-wsi a bit too concise. In particular, I wanted to try running the inference step on one WSI from the dataset to see that everything works with my software/hardware combination.

I would really appreciate it if you could release the pre-trained weights as asked in Issue https://github.com/BMIRDS/deepslide/issues/35. This will allow just trying your code on one example to see if everything works just on one WSI without training the models from scratch, which in turn will be a good indicator of how much code I can reuse from this repository.

Best wishes,
George Batchkala

**Comment by JosephDiPalma** [comment]
We currently are unable to share the pre-trained model weights publicly. Any potential changes to this decision will be reflected in an update on the README, should they happen.
