### ISSUE TITLE
Training Issues

### ISSUE THREAD

**Issue by Tejussurendran** [BMIRDS/deepslide#43]
@JosephDiPalma I was trying to train my model, however every time I attempt to train it, it appears to think that all the data is of the same class type. I am not sure why this is occurring however I have tried training and testing numerous times and it is the same result every time. Along with that I am not able to generate a confidence value either. 

Any ideas as to why this may be happening?

Thank you!

**Comment by JosephDiPalma** [comment]
@Tejussurendran Could you please provide the data directory structure?
Also, did you generate the directories using our code, or separately?
