### ISSUE TITLE
Attention based classification in ResNet18

### ISSUE THREAD

**Issue by Tato14** [BMIRDS/deepslide#5]
Sorry for the spam, I am now digging a little bit more in your code.
I realize, your code does not implement the attention based method that you published previously. Instead, it used sliding window approach, right?

I was wondering if you tried to add an attention based pooling layer in the ResNet arquitecture.
Thanks!

**Comment by jasonwei20** [comment]
Feel free to read about the attention-based model here: [https://arxiv.org/abs/1811.08513](https://arxiv.org/abs/1811.08513). But we don't have this code available yet unfortunately.
