### ISSUE TITLE
Integrating my own model

### ISSUE THREAD

**Issue by timofeiryko** [BMIRDS/deepslide#51]
Hello! I'm just starting to dive into this area, so I apologize in advance for the probably obvious question.

You use ResNet model in your **utils_model.py**. Is it possible to **inegrate my own model into the framework**? I am trying to implement transfer learning for histopathology.

Will the pipeline work ok, if I will just rewtite the **create_model** function?

**Comment by JosephDiPalma** [comment]
Yes, the pipeline should work if you rewrite the `create_model()` function.
