### ISSUE TITLE
Dataset Download Problem

### ISSUE THREAD

**Issue by Rukhmini** [BMIRDS/deepslide#52]
Hello,

I am not able to download the dataset. The dataset links are sent as undefined in the mail like below:

DHMC_wsi_1.zip
File size: 16.2 GB
undefined

DHMC_wsi_2.zip
File size: 13.18 GB
undefined

DHMC_wsi_3.zip
File size: 13.96 GB
undefined

DHMC_wsi_4.zip
File size: 6.7 GB
undefined

MetaData_Release_1.0.csv
File size: 48.09 KB
undefined

MD5SUMS.txt
File size: 196 Bytes
undefined

Dataset Research Use Agreement.pdf
File size: 23.36 KB
undefined

Please let me know how can I download the dataset.

**Comment by ntomita** [comment]
Thanks for reporting. The service is currently under maintenance and thus links are not available right now. We temprarily disabled forms to avoid further confusion.

**Comment by Rukhmini** [comment]
Thanks for the information. Can you please let me know when the links will be available?

**Comment by ntomita** [comment]
I will update here for status change.

**Comment by ntomita** [comment]
@Rukhmini  Links are available again. I'm closing the issue.
