### ISSUE TITLE
Data preprocessing problem

### ISSUE THREAD

**Issue by Tato14** [BMIRDS/deepslide#6]
![issue](https://user-images.githubusercontent.com/33808607/55937476-5d512100-5c39-11e9-8b9c-5aaf583964e0.png)

Hi, 

I am having troubles with the preprocessing split/merge scripts. As you see in the attached image, the jpg tiles are not merged properly. All the images that I checked behave similarly. May be some problem in the 3_repiece_jpg_tiles.py?

Thanks

**Comment by jasonwei20** [comment]
It is hard for me to see where the error occurred based on this screenshot, as I can't match every tile in the right image to the tile in the left.
