### ISSUE TITLE
Train Data

### ISSUE THREAD

**Issue by wxyz-wjx** [BMIRDS/deepslide#61]
Could you please provid the trainning data?

**Comment by ntomita** [comment]
Unfortunately, we don't share the training data. However, you can still utilize our testing data for model validation available at [bmirds.github.io](https://bmirds.github.io/).

**Comment by wxyz-wjx** [comment]
Well understood, how do you validate using test data sets? What are the operation steps, can you verify the tutorial?


L&nbsp;aurus
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BMIRDS/deepslide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月30日(星期六) 凌晨2:34
***@***.***&gt;;
抄送:&nbsp;"L ***@***.******@***.***&gt;;
主题:&nbsp;Re: [BMIRDS/deepslide] Train Data (Issue #61)





 
Unfortunately, we don't share the training data. However, you can still utilize our testing data for model validation available at bmirds.github.io.
