### ISSUE TITLE
issue about all_wsi

### ISSUE THREAD

**Issue by Daisy5566** [BMIRDS/deepslide#9]
Hi~Would you tell about the structure of the all_wsi or give an example? I am confused about the input data. Thanks a lot

**Comment by jasonwei20** [comment]
all_wsi must contain subfolders of images labeled by class. For example, if your two classes are 'a' and 'n', you must have a/*.jpg with the images in class a and n/*.jpg with images in class n. I had this in comments in config.py, but now I just added it to the readme to make it more clear. Thanks for the issue!
